### ISSUE TITLE
Remove double borders on buttons

### ISSUE THREAD

**Issue by vovkkk** [andreibsk/win10-theme#1]
Hey, the theme looks really nice, but those double borders are out of place:

![](https://raw.githubusercontent.com/andreibsk/win10-theme/master/img/default_toggle_color.png)

Single borders are much better:

![2016-05-06_06-51-12](https://cloud.githubusercontent.com/assets/1975298/15061432/0c9a2f50-1357-11e6-8879-e108ee196c00.png)

It can be achieved by e.g. removing left border for btn-group-middle and btn-group-right:

![btn-group-middle](https://cloud.githubusercontent.com/assets/1975298/15061622/542666b6-1359-11e6-87f8-e082a40a5ad7.png)![btn-group-right](https://cloud.githubusercontent.com/assets/1975298/15061639/718925ae-1359-11e6-9bad-319aa49e5c05.png)

``` js
    {
        "class": "icon_button_control",
        "attributes": ["right"],
        "layer0.texture": "some/path/to/btn-group-right.png",
        "content_margin": [0]
    },
```

What you think?

**Comment by andreibsk** [comment]
Changed the border looks with 3ee679ac65d028ec230a326faef181b6a240ad9f. However it still looks a bit awkward on border highlight on hover for some of the buttons:
![default_toggle_color-hover](https://cloud.githubusercontent.com/assets/3344848/15066633/0b42241e-136b-11e6-9a1b-228169febc37.png)

I can't think of a solution for that, that doesn't involve disabling the border highlight or completely removing the border on that one side:
![default_toggle_color-hover-alt](https://cloud.githubusercontent.com/assets/3344848/15066781/232accf6-136c-11e6-92d2-8915c79a373b.png)

**Comment by vovkkk** [comment]
Ooh damn! I did not even know that there is hover state, until today.

Maybe doing it in VSCode-buttons-style would make sense:
![2016-05-06_16-12-31](https://cloud.githubusercontent.com/assets/1975298/15071410/186b360c-13ad-11e6-89e9-c61ebf028c94.png)
It should be possible with use of 3 layers, I’d imagine.

---

Do you have plan to support overlay scrollbars?

**Comment by andreibsk** [comment]
Are you referring to the overall style of the VSCode buttons or just the fact that they're split from one another?
I wasn't planning on supporting overlay scroll bars, but might add them. Do you generally use overlay scroll bars?

**Comment by vovkkk** [comment]
> they're split from one another

yep

> Do you generally use overlay scroll bars?

yep, I may send pull request, if you’d like; only after May 9th though, 10-11 or sth.

**Comment by andreibsk** [comment]
I took your advice and split the buttons. I believe 7217b4f0fe59bfd0ec27c89ea7e937315ac48672 closes this issue.
I'll have a look at overlay scroll bars the next few days.
